site_name: Unreal C++ Snabbreferens
site_url: https://unrealcpp.progdocs.se
repo_url: https://github.com/krank/unrealcpp-ref-mkdocs
edit_uri: edit/main/docs/
theme:
  name: material
  language: sv
  icon:
    logo: material/language-cpp
  font:
    text: Inter
    # code: IBM Plex Mono
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: green
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: green
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    # - content.action.edit
markdown_extensions:
  - toc:
      anchorlink: false
  - attr_list
  
  # Grids
  - md_in_html

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Mermaid diagrams
  - pymdownx.superfences: # Superfences also required for admonitions, code blocks...
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Admonitions
  - admonition
  - pymdownx.details

  # Emoji & icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Highlight, super/subscript, keyboard keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Captions
  - pymdownx.blocks.caption
plugins:
  - search
  - awesome-nav:
      filename: .nav.yml
extra_css:
  - style.css